# Generated by Django 4.0.6 on 2022-07-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(),
        ),
    ]
