# Generated by Django 4.0.6 on 2022-07-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
